# Build Plugin.Maui.Intercom (cross-platform projects).
#
# The iOS binding (src/macios/Intercom.iOS.Binding) is generated by
# swift-dotnet-bindings and can only build on macOS with Xcode 26+ — use
# eng/generate-ios-binding.sh there. On Windows this script builds the
# Android binding, the plugin and the sample (Android flavor).

Write-Host "Building Plugin.Maui.Intercom..." -ForegroundColor Cyan
Write-Host ""

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path

Push-Location $scriptPath
try {
    Write-Host "[1/3] Building Android Binding..." -ForegroundColor Yellow
    dotnet build "src\android\Intercom.Android.Binding\Intercom.Android.Binding.csproj"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Android Binding build failed" -ForegroundColor Red
        exit 1
    }

    Write-Host "[2/3] Building Main Library..." -ForegroundColor Yellow
    dotnet build "src\Plugin.Maui.Intercom\Plugin.Maui.Intercom.csproj"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Main Library build failed (note: requires a resolvable Plugin.Maui.Intercom.iOS.Binding package)" -ForegroundColor Red
        exit 1
    }

    Write-Host "[3/3] Building Sample App..." -ForegroundColor Yellow
    dotnet build "src\sample\MauiSample.csproj"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "WARNING: Sample App build had issues (this is optional)" -ForegroundColor Yellow
    }

    Write-Host ""
    Write-Host "Build Complete!" -ForegroundColor Green
} finally {
    Pop-Location
}
