# file: .github/workflows/publish.yml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI

  push:
    branches:
      - main
    paths:
      - 'src/Plugin.Maui.Intercom/**'
      - 'src/android/**'
      - 'src/macios/**'
      - '.github/workflows/publish.yml'

  pull_request:
    branches:
      - '*'
    paths:
      - 'src/Plugin.Maui.Intercom/**'
      - 'src/android/**'
      - 'src/macios/**'
      - '.github/workflows/publish.yml'

  release:
    types: [ published ]

env:
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

permissions: {}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          show-progress: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: 'global.json'

      - name: Install MAUI workloads
        run: dotnet workload install maui-android maui-ios

      - name: Determine Version
        id: minver
        run: |
            dotnet tool install --global minver-cli
            git fetch --tags
            git tag
            $version = minver --tag-prefix v --auto-increment minor --verbosity trace
            echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV
            echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Build and Pack Android Binding
        run: dotnet pack src/android/Intercom.Android.Binding/Intercom.Android.Binding.csproj --configuration Release --output ${{ env.NuGetDirectory }} -p:Version=${{ env.PACKAGE_VERSION }}

      - name: Build and Pack iOS Binding
        run: dotnet pack src/macios/Intercom.MaciOS.Binding/Intercom.MaciOS.Binding.csproj --configuration Release --output ${{ env.NuGetDirectory }} -p:Version=${{ env.PACKAGE_VERSION }}

      - name: Add Local NuGet Source
        run: dotnet nuget add source ${{ env.NuGetDirectory }} --name LocalPackages

      - name: Build
        run: dotnet build src/Plugin.Maui.Intercom/Plugin.Maui.Intercom.csproj --configuration Release -p:Version=${{ env.PACKAGE_VERSION }}

      - name: Pack
        run: dotnet pack src/Plugin.Maui.Intercom/Plugin.Maui.Intercom.csproj --configuration Release --output ${{ env.NuGetDirectory }} --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:Version=${{ env.PACKAGE_VERSION }}

      - name: Prepare Artifacts
        run: |
          mkdir -p ${{ env.NuGetDirectory }}/artifacts
          cp ${{ env.NuGetDirectory }}/*.nupkg ${{ env.NuGetDirectory }}/artifacts
          cp ${{ env.NuGetDirectory }}/*.snupkg ${{ env.NuGetDirectory }}/artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: |
            ${{ env.NuGetDirectory }}/artifacts/*.nupkg
            ${{ env.NuGetDirectory }}/artifacts/*.snupkg

  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5

      - name: NuGet login (OIDC → temp API key)
        uses: nuget/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish NuGet package
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
