<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-ios</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
    
    <!--
      Enable trim analyzers for class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <XCFramework>NewBindingiOS.xcframework</XCFramework>
    <Framework>NewBinding.framework</Framework>
    <ProjectResources>Intercom.MaciOS.Binding.resources</ProjectResources>
    <RID>ios-arm64</RID>
    <SharpieOutput>sharpie-out</SharpieOutput>
    <Namespace>$(RootNameSpace)</Namespace>
    <SDK>iphoneos18.2</SDK>
    <Scope>Headers Headers/NewBinding-Swift.h</Scope>
  </PropertyGroup>

  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
  </ItemGroup>

  <!-- Reference to Xcode project -->
  <ItemGroup>
    <XcodeProject Include="../native/NewBinding/NewBinding.xcodeproj">
      <SchemeName>NewBinding</SchemeName>
    </XcodeProject>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="cd $(OutDir)/$(ProjectResources)/$(XCFramework)/$(RID)/$(Framework)&#xA;&#xA;rm -rf $(SharpieOutput)&#xA;&#xA;sharpie bind --output=$(SharpieOutput) --namespace=$(Namespace) --sdk=$(SDK) --scope=$(Scope)" />
  </Target>
</Project>
