<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-ios</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>

    <!--
      Enable trim analyzers for class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <XCFramework>NewBindingiOS.xcframework</XCFramework>
    <Framework>NewBinding.framework</Framework>
    <ProjectResources>Intercom.MaciOS.Binding.resources</ProjectResources>
    <RID>ios-arm64</RID>
    <SharpieOutput>sharpie-out</SharpieOutput>
    <Namespace>$(RootNameSpace)</Namespace>
    <SDK>iphoneos</SDK>
    <Scope>Headers Headers/NewBinding-Swift.h</Scope>
  </PropertyGroup>

  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
  </ItemGroup>

  <!-- Reference to Xcode project -->
  <ItemGroup>
    <XcodeProject Include="../native/NewBinding/NewBinding.xcodeproj">
      <SchemeName>NewBinding</SchemeName>
    </XcodeProject>
  </ItemGroup>

  <ItemGroup>
    <NativeReference Include="libs/Intercom.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>true</ForceLoad>
      <SmartLink>false</SmartLink>
      <Visible>true</Visible>
      <Frameworks></Frameworks>
    </NativeReference>
  </ItemGroup>

  <!-- Make resource package creation more resilient -->
  <Target Name="_EnsureBindingResourcesExist" BeforeTargets="_CreateBindingResourcePackage">
    <Message Text="Ensuring binding resources are ready..." Importance="high" />
  </Target>
</Project>







